/**
 * Stage 12 — conversational create. `+ New agent` ensures agents/New agent/
 * on disk (through `createBot` → `agentEnsure`) and opens that agent's chat in
 * setup mode. The agent asks, in order, what to call it, what its job is and
 * (optionally) what to always keep in mind; the answers go through the sidecar
 * (`agentUpdateProfile`: rename on disk, agent.json, AGENTS.md) and the chat
 * becomes a normal chat on that agent.
 *
 * The questions are scripted here, not generated by the model: setup must
 * work before any GGUF is loaded and must never depend on the model following
 * instructions to write the profile. `runAgentTurn` is not called during setup.
 *
 * The step is derived from the transcript (how many answers the human has
 * given since setup began), so it survives a re-render and is testable
 * without React.
 */
import { agentSlug } from "./fs/scope-model.ts";

export type SetupStep = "name" | "job" | "description" | "done";

export const SETUP_STEPS: SetupStep[] = ["name", "job", "description"];

export const SETUP_SKIP_WORDS = new Set(["skip", "none", "no", "-", "nothing"]);

export function setupStepForAnswers(answers: number): SetupStep {
  return SETUP_STEPS[answers] ?? "done";
}

/** What the agent says at each step. `state` is what has been collected so far. */
export function setupPrompt(step: SetupStep, state: { name?: string; job?: string }): string {
  switch (step) {
    case "name":
      return "Hi — I'm your new agent. I have a folder but no name yet. What should I be called?";
    case "job":
      return `${state.name ?? "Got it"}. What's my job? One line is enough — it shows under my name in the roster.`;
    case "description":
      return `Anything I should always keep in mind? It goes into my AGENTS.md as standing instructions. Type "skip" to leave it for later.`;
    case "done":
      return `All set. I'm ${state.name ?? "ready"}${state.job ? ` — ${state.job}` : ""}. What's first?`;
  }
}

export type SetupAnswer = { ok: true; value: string } | { ok: false; error: string };

/** Validate one answer client-side (the sidecar re-validates names on disk). */
export function parseSetupAnswer(step: SetupStep, raw: string): SetupAnswer {
  const text = raw.trim().replace(/\s+/g, " ");
  if (step === "name") {
    if (!text) return { ok: false, error: "I need a name — even a short one." };
    if (text.length > 64) return { ok: false, error: "That's longer than 64 characters. Something shorter?" };
    if (/[\\/:*?"<>|]/.test(text) || text.startsWith(".") || text.endsWith(".")) {
      return { ok: false, error: `A name becomes my folder, so it can't contain \\ / : * ? " < > | or start or end with a dot. Try again?` };
    }
    if (agentSlug(text) !== text) return { ok: false, error: `"${text}" is not a valid folder name. Try again?` };
    return { ok: true, value: text };
  }
  if (step === "job") {
    if (!text) return { ok: false, error: "A few words about what I do — for example “Drafts launch briefs”." };
    return { ok: true, value: text.slice(0, 120) };
  }
  if (step === "description") {
    if (SETUP_SKIP_WORDS.has(text.toLowerCase())) return { ok: true, value: "" };
    return { ok: true, value: raw.trim() };
  }
  return { ok: false, error: "Setup is already finished." };
}

/** Collect the accepted answers out of a transcript slice (user messages since setup began). */
export function setupStateFromAnswers(answers: readonly string[]): { name?: string; job?: string; description?: string } {
  const [name, job, description] = answers;
  return {
    name: name !== undefined ? parseSetupAnswer("name", name).ok ? name.trim().replace(/\s+/g, " ") : undefined : undefined,
    job: job !== undefined ? job.trim().replace(/\s+/g, " ").slice(0, 120) : undefined,
    description: description !== undefined ? (SETUP_SKIP_WORDS.has(description.trim().toLowerCase()) ? "" : description.trim()) : undefined,
  };
}
